export default {
    backarrow: require('../assests/images/back.png'),
    bluearrow: require('../assests/images/blue_arrow.png'),
    bell: require('../assests/images/bell.png'),
    bluebell: require('../assests/images/blue_bell.png'),
    home: require('../assests/images/home.png'),
    profile: require('../assests/images/profile.png'),
    addbtn: require('../assests/images/addbtn.png'),
    blueHome: require('../assests/images/home_blue.png'),
    community: require('../assests/images/community.png'),
    blog: require('../assests/images/blog.png'),
    user: require('../assests/images/user.png'),
    background: require('../assests/images/background.png'),
    event: require('../assests/images/events.png'),
    foodswap: require('../assests/images/foodswap.png'),
    goal: require('../assests/images/goal.png'),
    reminder: require('../assests/images/reminder.png'),
    residentialUser: require('../assests/images/residential.png'),
    educationcampus: require('../assests/images/graduate.png'),
    environmentalOrg: require('../assests/images/partners.png'),
    roundcomment: require('../assests/images/round-shape.png'),
    white_logo: require('../assests/images/ecobin_white_logo.png'),
    green_round: require('../assests/images/green_round.png'),
}